version: '3.8'

services:
  python-grpc:
    build:
      context: ./python-service
    container_name: python-grpc
    ports:
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_NAME=ml_tenants
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  go-api:
    build:
      context: ./go-service
    container_name: go-api
    ports:
      - "8080:8080"
    depends_on:
      - python-grpc

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: ml_tenants
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
